// Genre normalization for Last.fm tags.
//
// Last.fm tags are crowd-sourced and messy: the same genre shows up under several
// spellings (hiphop / hip-hop / hip hop), and the feed is padded with tags that
// aren't genres — geography, artist names, and personal/meta junk. This collapses
// the variants and drops the non-genres so the genre COUNT, the filter CHIPS, and
// the include/exclude MATCHING all work off clean, canonical strings.
//
// Applied at read/display + filter-match time (not baked into the cache), so it
// takes effect on the existing library with no re-fetch. Kept deliberately OUT of
// the tuned vibe-scoring path in preFilter (scoreTrack / VIBE_TO_GENRES).
//
// The drop/alias sets below were tuned against a real ~600-artist library dump.
// The bulk of the long tail (one-off artist names, memes, typos) is a singleton
// and is handled by the min-artist threshold in LibraryScreen, not enumerated here;
// these sets target the HIGH-frequency junk that would otherwise reach the chips.

// Personal / sentiment / meta tags that aren't genres.
const DROP_TAGS = new Set([
  'vocalist',
  'vocalists',
  'male vocalists',
  'female vocalists',
  'male vocalist',
  'female vocalist',
  'female',
  'male',
  'instrumental',
  'guitar',
  'saxophone',
  'piano',
  'guitarist',
  'band',
  'music',
  'song',
  'songs',
  'cover',
  'covers',
  'radio',
  'spotify',
  'vinyl',
  'my top songs',
  'the best',
  'the best',
  'best',
  'good',
  'bad',
  'cool',
  'nice',
  'awesome',
  'beautiful',
  'amazing',
  'catchy',
  'boring',
  'silly',
  'funny',
  'weirdo',
  'cute',
  'sexy',
  'sex',
  'ass',
  'milkers',
  'edging',
  'hairy chest',
  'woman beater',
  'beast boy',
  'fire',
  'swag',
  'ai',
  'queer',
  'urban',
  'favorite',
  'favorites',
  'favourite',
  'favourites',
  'favorite songs',
  'love',
  'love at first listen',
  'under 2000 listeners',
  'seen live',
  '4 stars',
  'clip farming',
  'tiktok',
  'tiktokcore',
  'sped up',
  'remix',
  'live',
  'dj',
  'djs',
  'producer',
  'rapper',
  'artist',
  'actors',
  'actress',
  'composer',
  'girl group',
  'boy group',
  'idol',
  'text',
  'tv show',
  'meme',
  'all',
  'various',
  'various artists',
  'other',
  'misc',
  'unknown',
  'genre',
  'club',
  'beats',
  'in spanish',
  'passion of discovery',
  'mpr',
  'jpm',
  'c',
  'go',
  'vamp',
  'jeepster',
  'graveem1nd',
  'krushclub',
  'odecore',
  'sweet soulmusic',
  'sonic hispeed omega',
  'sonic hybrid orchestra',
  'funk_add_to_lidarr_batch_16',
  'better than selena gomez',
  // Franchises / shows / events — not genres.
  'one piece',
  'persona 4',
  'league of legends',
  'touhou',
  'glee',
  'la la land',
  'spring awakening',
  'broadway',
  'musical theatre',
  'eurovision',
  'sxsw 2017',
  'niconico',
  'the voice',
])

// Places — countries, demonyms, regions, US states, cities. Exact-match only, so
// genre tags that merely CONTAIN a place ("japanese city pop", "uk garage",
// "french hip hop") are kept.
const DROP_PLACES = new Set([
  // Countries / nations
  'united states',
  'united states of america',
  'usa',
  'us',
  'america',
  'uk',
  'britain',
  'england',
  'japan',
  'nihon',
  'korea',
  'south korea',
  'north korea',
  'china',
  'canada',
  'australia',
  'new zealand',
  'germany',
  'deutschland',
  'france',
  'spain',
  'italy',
  'brazil',
  'mexico',
  'india',
  'sweden',
  'norway',
  'finland',
  'denmark',
  'iceland',
  'netherlands',
  'russia',
  'poland',
  'ukraine',
  'austria',
  'belgium',
  'ireland',
  'scotland',
  'wales',
  'portugal',
  'greece',
  'turkey',
  'cuba',
  'puerto rico',
  'philippines',
  'malaysia',
  'singapore',
  'thailand',
  'vietnam',
  'indonesia',
  'nigeria',
  'kenya',
  'south africa',
  'algeria',
  'romania',
  'hungary',
  'switzerland',
  'samoa',
  'argentina',
  'colombia',
  'jamaica',
  'africa',
  'europe',
  'european',
  'asia',
  'asian',
  // Demonyms / languages
  'american',
  'british',
  'english',
  'japanese',
  'korean',
  'chinese',
  'canadian',
  'australian',
  'german',
  'french',
  'spanish',
  'italian',
  'brazilian',
  'mexican',
  'indian',
  'swedish',
  'norwegian',
  'finnish',
  'danish',
  'icelandic',
  'dutch',
  'russian',
  'polish',
  'ukrainian',
  'austrian',
  'belgian',
  'irish',
  'scottish',
  'welsh',
  'portuguese',
  'greek',
  'turkish',
  'cuban',
  'filipino',
  'malaysian',
  'singaporean',
  'thai',
  'vietnamese',
  'indonesian',
  'nigerian',
  'kenyan',
  'algerian',
  'romanian',
  'hungarian',
  'swiss',
  'samoan',
  'jamaican',
  'latino',
  'latina',
  'deutsch',
  // US states
  'california',
  'texas',
  'florida',
  'new jersey',
  'michigan',
  'virginia',
  'alabama',
  'missouri',
  'north carolina',
  'south carolina',
  'georgia',
  'illinois',
  'ohio',
  'pennsylvania',
  'washington',
  'oregon',
  'colorado',
  'arizona',
  'nevada',
  'tennessee',
  'kentucky',
  'louisiana',
  'massachusetts',
  'maryland',
  'minnesota',
  'wisconsin',
  'indiana',
  'iowa',
  // Cities / regions
  'atlanta',
  'chicago',
  'new york',
  'brooklyn',
  'detroit',
  'memphis',
  'bay area',
  'west coast',
  'east coast',
  'toronto',
  'montreal',
  'seattle',
  'pittsburgh',
  'london',
  'dc',
  'washington dc',
  'miami',
  'essex',
  'philadelphia',
  'compton',
  'dallas',
  'san diego',
  'los angeles',
  'la',
  'houston',
  'boston',
  'austin',
  'nashville',
  'portland',
  'denver',
  'oakland',
  'san francisco',
  'birmingham',
  'manchester',
  'liverpool',
  'glasgow',
  'dublin',
  'berlin',
  'paris',
  'tokyo',
  'osaka',
  'seoul',
  'sydney',
  'melbourne',
])

// Artist / person names that get mis-tagged as genres. Not exhaustive — one-off
// names are singletons dropped by the threshold; these are the recurring ones.
const DROP_ARTISTS = new Set([
  'travis scott',
  'kanye west',
  'kanye',
  'lana del rey',
  'justin bieber',
  'chris brown',
  'ariana grande',
  'keyshia cole',
  'jay park',
  'mf doom',
  'jay-z',
  'jay z',
  'selena gomez',
  'nelly',
  'raekwon',
  'booba',
  'ofwgkta',
  'twice',
  'bts',
  'jungkook',
  'nct',
  'block b',
  'rosé',
  'rose',
  'yumi nu',
])

// Variant / misspelling → canonical. Keys are compared after basic cleanup
// (lowercase, trimmed, whitespace collapsed, `rnb`→`r&b` already applied).
// Canonical forms stay compatible with the substrings preFilter's VIBE_TO_GENRES
// uses (keep the hyphen in "lo-fi"/"post-rock", the space in "hip hop").
const GENRE_ALIASES: Record<string, string> = {
  hiphop: 'hip hop',
  'hip-hop': 'hip hop',
  'hip hop music': 'hip hop',
  rap: 'hip hop',
  'trip-hop': 'trip hop',
  triphop: 'trip hop',
  'r n b': 'r&b',
  'rhythm and blues': 'r&b',
  'rhythm & blues': 'r&b',
  lofi: 'lo-fi',
  'lo fi': 'lo-fi',
  'low-fi': 'lo-fi',
  synthpop: 'synth pop',
  'synth-pop': 'synth pop',
  'neo soul': 'neo-soul',
  'alt rock': 'alternative rock',
  'alt-rock': 'alternative rock',
  altrock: 'alternative rock',
  alternative: 'alternative rock',
  indierock: 'indie rock',
  indiepop: 'indie pop',
  dreampop: 'dream pop',
  'dream-pop': 'dream pop',
  'post punk': 'post-punk',
  postpunk: 'post-punk',
  'post rock': 'post-rock',
  postrock: 'post-rock',
  'nu-metal': 'nu metal',
  numetal: 'nu metal',
  'new-wave': 'new wave',
  newwave: 'new wave',
  electronica: 'electronic',
  eletronic: 'electronic',
  edm: 'electronic',
  dnb: 'drum and bass',
  'drum n bass': 'drum and bass',
  'drum & bass': 'drum and bass',
  "drum'n'bass": 'drum and bass',
  'rock n roll': 'rock and roll',
  "rock 'n' roll": 'rock and roll',
  "rock'n'roll": 'rock and roll',
  'singer songwriter': 'singer-songwriter',
  'classic-rock': 'classic rock',
  'hard-rock': 'hard rock',
  'pop-punk': 'pop punk',
  poppunk: 'pop punk',
  kpop: 'k-pop',
  'k pop': 'k-pop',
  jpop: 'j-pop',
  'j pop': 'j-pop',
  jrock: 'j-rock',
  'j rock': 'j-rock',
  cpop: 'c-pop',
  'c pop': 'c-pop',
  ost: 'soundtrack',
  'dance-pop': 'dance pop',
}

// Canonicalize a single raw tag. Returns null for tags that should be dropped.
export function canonicalizeGenre(raw: string): string | null {
  let g = raw
    .trim()
    .toLowerCase()
    .replace(/^["'`]+|["'`]+$/g, '')
    .replace(/\s+/g, ' ')
    .trim()

  if (!g || g.length < 2) return null
  // Fold the "rnb" spelling to "r&b" wherever it appears as a word: collapses
  // rnb / alternative rnb / k-rnb / indie rnb / prog-rnb in one shot.
  g = g.replace(/\brnb\b/g, 'r&b')

  if (DROP_TAGS.has(g) || DROP_PLACES.has(g) || DROP_ARTISTS.has(g)) return null
  // Decade tags ("90s", "1990s", "00s", "80's") and bare years ("2002").
  if (/^(19|20)?\d0['’]?s$/.test(g)) return null
  if (/^(19|20)\d{2}$/.test(g)) return null

  return GENRE_ALIASES[g] ?? g
}

// Canonicalize + dedupe a list of tags (order preserved by first appearance).
export function canonicalizeGenres(list: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const raw of list) {
    const g = canonicalizeGenre(raw)
    if (g && !seen.has(g)) {
      seen.add(g)
      out.push(g)
    }
  }
  return out
}
